### ISSUE TITLE
Could you remove this console.log in the next version?

### ISSUE THREAD

**Issue by grofzero** [reinerBa/Vue-Responsive#4]
https://github.com/reinerBa/Vue-Responsive/blob/b9f9cc3a587b6997ff66eecc1483786e8d26487e/src/index.js#L79

hi, 

Could you remove this console.log in the next version?

Thank you very much,
grofzero

**Comment by reinerBa** [comment]
Done with f255fc6208c4f783883619e29d7380248369ca89 Thanks!
