### ISSUE TITLE
Unexpected token: name (useClass)

### ISSUE THREAD

**Issue by allfreelancers** [reinerBa/Vue-Responsive#5]
webpack build errors:
Unexpected token: name (useClass)
messages.5ed1be89d537d0148e3b.js from UglifyJs

**Comment by reinerBa** [comment]
Ok that should not happen. Do you get this message for the file in the master branche or from npm?
This variable only occures in three lines which seems to be ok, i need to replicate the error.

**Comment by allfreelancers** [comment]
@reinerBa from npm 
what data is still needed?

**Comment by reinerBa** [comment]
I was unable to reproduce that problem.
