### ISSUE TITLE
No work in IE11

### ISSUE THREAD

**Issue by frandarko** [reinerBa/Vue-Responsive#6]
hello,

I see that vue-responsive not work in IE11. It´s correct?
I tested in 2 diferents machines.
This demo neither work:
https://reiner.bamberger.rocks/Vue-Responsive/dist/#demoFour

thks

**Comment by jasonrhaddix** [comment]
I have the same issue and this is due to a template string being used in the index.js file - which are not supported in IE11

```
[...
    for (let key in self._rPermissions[binding.arg]) {
      validInputs.push(key)
      validPositiv.push(key)
      validInputs.push(`hidden-${key}`)  <-----------
    }
...]
```

I have opened a PR to fix this.

**Comment by reinerBa** [comment]
The bug is fixed but the public demo doesn`t works in IE11 because of webpack
