### ISSUE TITLE
This is not a issue.

### ISSUE THREAD

**Issue by Zhengyangma** [reinerBa/Vue-Responsive#7]
But, I am currently working on a typescript -based vue project, so,

is there any approach to Vue.use(responsive) in typescript main entrance ts file?

I can use it to do a js-style coding but, it's not effective globally.

**Comment by Shamus03** [comment]
Just put `// @ts-ignore` above your import and/or `Vue.use(responsive)`.  This is the most simple general solution for using libraries without TypeScript definitions.  The alternative is creating definitions yourself (or opening a PR to add them).

**Comment by Zhengyangma** [comment]
> Just put `// @ts-ignore` above your import and/or `Vue.use(responsive)`. This is the most simple general solution for using libraries without TypeScript definitions. The alternative is creating definitions yourself (or opening a PR to add them).

thank you, very much, I am sorry to notice this reply so late
